# 镜像(glance)
# 列出您可以访问的镜像
openstack image list
if false; then
+--------------------------------------+---------------------------------------------+
| ID                                   | Name                                        |
+--------------------------------------+---------------------------------------------+
| f089408b-5125-4dbf-b499-c8889dcc0aa4 | trove-mongodb-3.2                           |
| be582494-6df8-4519-b4f7-164119ae2a01 | sdckkk                                      |
| 7b6fadf3-b6f7-41d0-a8a7-b69eeaecbfb4 | trove-mysql-5.6                             |
| 271a456b-5626-45b4-9592-45e025e87eab | sahara-mitaka-spark-1.6.0-ubuntu            |
| ec0f5c88-705f-4a4e-9ec0-a6e91a6735bc | sahara-mitaka-vanilla-hadoop-2.7.1-centos-7 |
| f0cb1b5d-d427-41c7-bc32-e6f9f650fc0b | 监控测试-32                                 |
| 3d73dbc4-c5d1-49f0-9012-1b58ada6d35d | 34                                          |
| 5a289be0-246e-409c-9a2e-bf11fa97616c | 镜像_1023_003                               |
| 30121771-c7df-452d-b586-7cec893977c2 | aebkkk                                      |
| 708ae00b-c381-4f34-8910-5fdf49e4364f | test-ci                                     |
| 95c9a732-0846-4f1b-8ef0-08b71619041b | test                                        |
| 5905debd-e174-447c-af66-68fb6f9016b4 | 11                                          |
| c1a09e63-65e3-4239-9cbc-3843d7cf71be | ssh                                         |
| cea0db6d-cee3-4682-8807-0aa4e7737c4f | linuxsnap                                   |
| f27347b6-4b5e-48ba-b14f-80759e017bce | 6                                           |
| 05f887b9-22bc-43a0-8894-4e340c0a4da8 | ss                                          |
| 34ac7aed-1c0b-4a10-bb87-37aeea96e718 | why                                         |
| 33676c39-07c5-4c6e-9f24-f37e2c9f798e | pop                                         |
| 8e8a4ccb-bff6-4004-95e6-b8d479eb3b96 | si                                          |
| 778eef85-c0b7-4077-aa67-e6a207492909 | trove-redis                                 |
| 58443a3b-24d5-412e-a89a-f033c00b92e0 | boot_image_windows                          |
| a6307b14-3432-4750-bcfb-a3e5f2fffcf6 | boot_image_linux                            |
| 93c3da10-4af0-4580-a52a-1eeebd0d9161 | cirros                                      |
+--------------------------------------+---------------------------------------------+
fi
# 删除指定的镜像
openstack image delete IMAGE
# 描述一个指定的镜像
openstack image show 93c3da10-4af0-4580-a52a-1eeebd0d9161
if false; then
+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Field            | Value                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| checksum         | 8e214144c63d27c4ac0cbc379cba161d                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| container_format | bare                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| created_at       | 2017-08-31T07:27:07Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| disk_format      | raw                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| file             | /v2/images/93c3da10-4af0-4580-a52a-1eeebd0d9161/file                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| id               | 93c3da10-4af0-4580-a52a-1eeebd0d9161                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| min_disk         | 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| min_ram          | 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| name             | cirros                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| owner            | 253a9e23972f4e7ba6fa8a17249b8053                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| properties       | bootpath='2', description='21313123123', direct_url='rbd://3346aa25-ce27-49bc-b8b4-b4628b11d0d1/images/93c3da10-4af0-4580-a52a-1eeebd0d9161/snap', hw_boot_menu='False', hw_qemu_guest_agent='yes', hw_vif_model='virtio', img_config_drive='optional', inject_without_cloudinit='no', libguestfs_only='no', locations='[{u'url': u'rbd://3346aa25-ce27-49bc-b8b4-b4628b11d0d1/images/93c3da10-4af0-4580-a52a-1eeebd0d9161/snap', u'metadata': {}}]', os_type='linux', owner_specified.shade.md5='8e214144c63d27c4ac0cbc379cba161d', owner_specified.shade.object='images/cirros', owner_specified.shade.sha256='4fabdc4e6e37381110b3fa804e543823480ea58b1db5deaadc49decca4a5caf5' |
| protected        | False                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| schema           | /v2/schemas/image                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| size             | 115153920                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| status           | active                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| updated_at       | 2017-09-06T11:31:27Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| virtual_size     | None                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| visibility       | public                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
fi

# 更新镜像
openstack image set IMAGE
# 上传内核镜像
openstack image create "cirros-threepart-kernel" --disk-format aki --container-format aki --public --file ~/images/cirros-0.3.5-x86_64-kernel
# 上传RAM镜像
openstack image create "cirros-threepart-ramdisk" --disk-format ari --container-format ari --public --file ~/images/cirros-0.3.5-x86_64-initramfs
# 上传第三方镜像
openstack image create "cirros-threepart" --disk-format ami  --container-format ami --public --property kernel_id=$KID-property ramdisk_id=$RID --file ~/images/cirros-0.3.5-x86_64-rootfs.img
# 注册raw镜像
openstack image create "cirros-raw" --disk-format raw  --container-format bare --public --file ~/images/cirros-0.3.5-x86_64-disk.img